name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - name: Setup Bun
        uses: oven-sh/setup-bun@f4d14e03ff726c06358e5557344e1da148b56cf7 # v1.2.2
      - name: Install dependencies
        run: bun install
      - name: Build react-native-app-clip
        run: bun run build
